import type { CustomerProject, DealBaseRecord, DeliveryBatch, DeliveryTarget, Lead, Quotation, Supplier } from './types'

export const initialLeads: Lead[] = [
  {
    id: 'L20260707001',
    name: '陈先生',
    phone: '13800138001',
    city: '上海',
    interestedBrand: '问界',
    interestedModel: 'M9',
    budget: '40-50万',
    purchaseTimeframe: 'within_30_days',
    source: '抖音线索',
    status: 'valid',
    createdAt: '2026-07-07 09:20',
    owner: '运营A',
    note: '关注六座版本，接受电话回访。',
    followUps: [
      {
        id: 'F20260707001',
        time: '2026-07-07 09:35',
        operator: '运营A',
        content: '已确认客户关注问界 M9 六座版，预算充足，可优先进入有效线索池。',
      },
    ],
  },
  {
    id: 'L20260707002',
    name: '李女士',
    phone: '13900139002',
    city: '杭州',
    interestedBrand: '理想',
    interestedModel: 'L7',
    budget: '30-40万',
    purchaseTimeframe: 'within_90_days',
    source: '小红书表单',
    status: 'pending_clean',
    createdAt: '2026-07-07 10:05',
    owner: '运营B',
    note: '需要确认是否接受经销商联系。',
    followUps: [
      {
        id: 'F20260707002',
        time: '2026-07-07 10:30',
        operator: '运营B',
        content: '电话未接通，待二次确认购车时间和接收回访意愿。',
      },
    ],
  },
  {
    id: 'L20260707003',
    name: '王先生',
    phone: '13700137003',
    city: '成都',
    interestedBrand: '比亚迪',
    interestedModel: '汉 DM-i',
    budget: '20-30万',
    purchaseTimeframe: 'within_7_days',
    source: '懂车帝',
    status: 'valid',
    createdAt: '2026-07-07 10:30',
    owner: '运营A',
    note: '已确认购车时间，优先交付。',
    followUps: [
      {
        id: 'F20260707003',
        time: '2026-07-07 10:45',
        operator: '运营A',
        content: '客户 7 天内购车，接受本地经销商联系，线索质量高。',
      },
    ],
  },
  {
    id: 'L20260707004',
    name: '赵女士',
    phone: '13800138001',
    city: '苏州',
    interestedBrand: '问界',
    interestedModel: 'M7',
    budget: '25-35万',
    purchaseTimeframe: 'unknown',
    source: 'Excel导入',
    status: 'duplicate',
    createdAt: '2026-07-07 11:12',
    owner: '运营C',
    note: '手机号与陈先生重复，需合并或作废。',
    followUps: [
      {
        id: 'F20260707004',
        time: '2026-07-07 11:20',
        operator: '运营C',
        content: '系统识别手机号重复，暂不进入交付批次。',
      },
    ],
  },
  {
    id: 'L20260707005',
    name: '周先生',
    phone: '13600136005',
    city: '广州',
    interestedBrand: '特斯拉',
    interestedModel: 'Model Y',
    budget: '25-35万',
    purchaseTimeframe: 'within_30_days',
    source: '百度搜索',
    status: 'delivered',
    createdAt: '2026-07-07 13:46',
    owner: '运营B',
    note: '已交付给华南新能源平台。',
    followUps: [
      {
        id: 'F20260707005',
        time: '2026-07-07 14:12',
        operator: '管理员',
        content: '已随 B20260707001 批次交付，等待接收方反馈。',
      },
    ],
  },
]

export const initialTargets: DeliveryTarget[] = [
  {
    id: 'T001',
    name: '华南新能源线索平台',
    type: 'platform',
    contact: '刘经理',
    phone: '18600010001',
    status: 'active',
    note: '偏好一线和新一线城市线索。',
  },
  {
    id: 'T002',
    name: '某主机厂直营中心',
    type: 'oem',
    contact: '张总',
    phone: '18600010002',
    status: 'active',
    note: '重点接收问界、理想相关意向线索。',
  },
]

export const initialBatches: DeliveryBatch[] = [
  {
    id: 'B20260707001',
    targetId: 'T001',
    leadIds: ['L20260707005'],
    createdBy: '管理员',
    createdAt: '2026-07-07 14:10',
    status: 'delivered',
    note: '首批测试交付，等待对方反馈。',
  },
]

export const initialSuppliers: Supplier[] = [
  {
    id: 'S20260707001',
    name: '星河汽车线索渠道',
    type: 'channel',
    contact: '黄经理',
    phone: '18500020001',
    contractStart: '2026-06-01',
    contractEnd: '2027-05-31',
    paymentMode: 'postpaid',
    accountPeriod: '30_days',
    status: 'active',
    note: '主供短视频表单线索，按有效线索结算。',
  },
  {
    id: 'S20260707002',
    name: '智数车购数据服务',
    type: 'data',
    contact: '林总',
    phone: '18500020002',
    contractStart: '2026-01-15',
    contractEnd: '2026-08-05',
    paymentMode: 'prepaid',
    accountPeriod: 'cash',
    status: 'active',
    note: '主供新能源意向人群包，合约即将进入续签沟通期。',
  },
  {
    id: 'S20260707003',
    name: '华东车友社群渠道',
    type: 'channel',
    contact: '周主管',
    phone: '18500020003',
    contractStart: '2026-03-01',
    contractEnd: '2026-12-31',
    paymentMode: 'postpaid',
    accountPeriod: '15_days',
    status: 'paused',
    note: '近期重复率偏高，暂停接入新线索。',
  },
]

export const initialDealBaseRecords: DealBaseRecord[] = [
  {
    id: 'D20260707001',
    city: '上海',
    brand: '问界',
    dealer: '上海浦东问界体验中心',
    contact: '沈经理',
    phone: '18700030001',
    position: '销售经理',
    supplyModel: '问界 M9 六座版',
    supplyContent: '可预占 5 台，优先匹配 30 天内购车客户。',
    supplyProof: '微信确认截图编号 WX-M9-0707',
    supplyTime: '2026-07-07 18:00',
    isValid: true,
    paymentMode: 'postpaid',
    amount: 12000,
    capacity: '5台/7天',
    owner: '开拓运营A',
    payer: '财务王',
    paymentTime: '成交后 T+7',
    status: 'reserved',
    isSuccess: false,
    failureReason: '',
    companyBearsCost: false,
    note: '已有客户需求可匹配，需跟进交割窗口。',
  },
  {
    id: 'D20260707002',
    city: '杭州',
    brand: '理想',
    dealer: '杭州滨江理想中心',
    contact: '钱主管',
    phone: '18700030002',
    position: '门店主管',
    supplyModel: '理想 L7 Pro',
    supplyContent: '周内可提供 3 台现车成交资源。',
    supplyProof: '邮件确认编号 EMAIL-L7-0706',
    supplyTime: '2026-07-08 12:00',
    isValid: true,
    paymentMode: 'prepaid',
    amount: 8000,
    capacity: '3台/5天',
    owner: '开拓运营B',
    payer: '财务李',
    paymentTime: '2026-07-07 15:00',
    status: 'delivered',
    isSuccess: false,
    failureReason: '',
    companyBearsCost: false,
    note: '已预付，必须追踪成交结果。',
  },
  {
    id: 'D20260707003',
    city: '成都',
    brand: '比亚迪',
    dealer: '成都高新比亚迪王朝店',
    contact: '杜店长',
    phone: '18700030003',
    position: '店长',
    supplyModel: '汉 DM-i',
    supplyContent: '客户到店未确认，门店口径不稳定。',
    supplyProof: '电话录音 REC-HAN-0705',
    supplyTime: '2026-07-05 16:30',
    isValid: false,
    paymentMode: 'prepaid',
    amount: 5000,
    capacity: '2台/3天',
    owner: '开拓运营A',
    payer: '财务王',
    paymentTime: '2026-07-05 17:20',
    status: 'failed',
    isSuccess: false,
    failureReason: '客户不算成交，门店未认定有效成交。',
    companyBearsCost: true,
    note: '成本需公司承担，后续该门店需降权观察。',
  },
]

export const initialQuotations: Quotation[] = [
  {
    id: 'Q20260708001',
    customerName: '易车华东 KA 询价',
    demander: '客户张经理',
    demandTime: '2026-07-08 09:30',
    cityScope: ['上海', '杭州', '苏州'],
    carBrand: '问界',
    carModel: 'M9',
    contentType: 'lead',
    demandVolume: '3000条/月',
    targetPrice: 18,
    needsQuotation: true,
    requiresPingAnPolicy: false,
    supportsPreciseDelivery: true,
    submissionMethod: 'link',
    canQrToLinkWhitelist: false,
    requiresVerificationCode: false,
    requiresDeal: false,
    requiredDealRatio: '',
    requiresArrival: false,
    judgementType: 'system',
    judgementStandard: '系统判定有效线索，首触有效率不低于 65%。',
    upstreamQuotePrice: 13,
    upstreamCapacity: '2500条/月',
    upstreamSupplier: '星河汽车线索渠道',
    ownedQuotePrice: 15,
    ownedCapacity: '1200条/月',
    ownedOwner: '自有渠道A',
    recommendedPrice: 18,
    grossMargin: 0.22,
    salesOwner: '销售A',
    operationOwner: '运营A',
    channelOwner: '渠道运营A',
    status: 'quoted',
    requirementNote: '客户提供链接录入，支持精准城市和车型下发。',
    quoteNote: '建议优先上游承接，自有渠道做补量。',
  },
  {
    id: 'Q20260708002',
    customerName: '懂车帝到店成交询价',
    demander: '客户王总',
    demandTime: '2026-07-08 10:20',
    cityScope: ['杭州', '宁波'],
    carBrand: '理想',
    carModel: 'L7',
    contentType: 'arrival',
    demandVolume: '200组到店/月',
    targetPrice: 120,
    needsQuotation: true,
    requiresPingAnPolicy: false,
    supportsPreciseDelivery: true,
    submissionMethod: 'qr_code',
    canQrToLinkWhitelist: false,
    requiresVerificationCode: true,
    requiresDeal: true,
    requiredDealRatio: '成交比例不低于 8%',
    requiresArrival: true,
    judgementType: 'mixed',
    judgementStandard: '客户系统到店为主，我方需补充录音和门店截图。',
    upstreamQuotePrice: 85,
    upstreamCapacity: '150组/月',
    upstreamSupplier: '智数车购数据服务',
    ownedQuotePrice: 95,
    ownedCapacity: '80组/月',
    ownedOwner: '产能中心B',
    recommendedPrice: 135,
    grossMargin: 0.3,
    salesOwner: '销售B',
    operationOwner: '运营B',
    channelOwner: '渠道运营B',
    status: 'requirement_confirming',
    requirementNote: '二维码如不能转链接白名单，需确认录入成本和验证码接收方式。',
    quoteNote: '风险高，报价需覆盖验证码、人工作业和凭证成本。',
  },
  {
    id: 'Q20260708003',
    customerName: '华南直播基地线索询价',
    demander: '客户李经理',
    demandTime: '2026-07-08 11:10',
    cityScope: ['广州', '深圳', '佛山'],
    carBrand: '比亚迪',
    carModel: '汉 DM-i',
    contentType: 'deal',
    demandVolume: '1000条/场',
    targetPrice: 0,
    needsQuotation: true,
    requiresPingAnPolicy: true,
    supportsPreciseDelivery: false,
    submissionMethod: 'spreadsheet',
    canQrToLinkWhitelist: false,
    requiresVerificationCode: false,
    requiresDeal: true,
    requiredDealRatio: '按成交单结算，无固定比例',
    requiresArrival: false,
    judgementType: 'proof',
    judgementStandard: '我方提供保单截图和成交凭证，客户复核。',
    upstreamQuotePrice: 0,
    upstreamCapacity: '待上游反馈',
    upstreamSupplier: '',
    ownedQuotePrice: 65,
    ownedCapacity: '600条/场',
    ownedOwner: '产能中心C',
    recommendedPrice: 90,
    grossMargin: 0.28,
    salesOwner: '销售C',
    operationOwner: '运营C',
    channelOwner: '产能中心C',
    status: 'sourcing',
    requirementNote: '表格交付，重点确认平安保单凭证格式。',
    quoteNote: '自有产能可先报，等待上游补充量级。',
  },
]

export const initialCustomerProjects: CustomerProject[] = [
  {
    id: 'P20260707001',
    customerName: '易车华东 KA 项目',
    projectType: 'platform',
    supplyTarget: 'yiche',
    oemBrand: '问界',
    isLiveBusiness: false,
    platformBusinessName: 'ka',
    supplyContentType: 'lead',
    demandVolume: '3000条/月',
    pushTime: '每日 10:00 / 16:00',
    salesOwner: '销售A',
    operationOwner: '运营A',
    status: 'active',
    requiresFirstTouch: true,
    effectiveRateRequirement: '有效率不低于 65%',
    systemDedupValid: true,
    pushSuccess: true,
    supportsPreciseDelivery: true,
    dealCycle: 't3',
    requiresDealProof: true,
    dealProofType: '图片',
    requiresArrivalRecording: false,
    requiresArrivalProof: false,
    requiresSystemArrivalConfirm: false,
    maxDealsPerStore: '不超过3单',
    storeRequirementNote: '超出需提前报备。',
    contractSigned: true,
    contractNo: 'HT-YC-KA-202607',
    downPaymentAmount: 50000,
    downPaymentReceived: true,
    settlementMode: 'monthly',
    accountPeriod: '30_days',
    invoiceType: 'general_taxpayer',
    unitPrice: 18,
    finalUnitPrice: 16,
    finalSettlementRatio: 0.9,
    finalSettlementAmount: 43200,
    settlementStandard: '客户给出数据为准',
    lossRatio: 0.08,
    settlementNote: '月结，按客户最终有效数据核算。',
    requirementNote: '普通线索按首触和有效率双标准验收。',
  },
  {
    id: 'P20260707002',
    customerName: '懂车帝到店成交项目',
    projectType: 'platform',
    supplyTarget: 'dongchedi',
    oemBrand: '理想',
    isLiveBusiness: false,
    platformBusinessName: 'arrival',
    supplyContentType: 'arrival',
    demandVolume: '200组到店/月',
    pushTime: '工作日 12:00 前',
    salesOwner: '销售B',
    operationOwner: '运营B',
    status: 'pending',
    requiresFirstTouch: false,
    effectiveRateRequirement: '到店确认率不低于 50%',
    systemDedupValid: true,
    pushSuccess: false,
    supportsPreciseDelivery: true,
    dealCycle: 't30',
    requiresDealProof: true,
    dealProofType: '图片/视频',
    requiresArrivalRecording: true,
    requiresArrivalProof: true,
    requiresSystemArrivalConfirm: true,
    maxDealsPerStore: '不超过3单',
    storeRequirementNote: '单店超 3 单需备注说明。',
    contractSigned: false,
    contractNo: '',
    downPaymentAmount: 30000,
    downPaymentReceived: false,
    settlementMode: 'project',
    accountPeriod: '15_days',
    invoiceType: 'small_scale',
    unitPrice: 120,
    finalUnitPrice: 0,
    finalSettlementRatio: 0,
    finalSettlementAmount: 0,
    settlementStandard: '双方确认',
    lossRatio: 0.12,
    settlementNote: '首付款未到账，暂不大批量推送。',
    requirementNote: '需要到店录音和系统到店确认。',
  },
  {
    id: 'P20260707003',
    customerName: '华南直播基地线索供量',
    projectType: 'live_base',
    supplyTarget: 'live_base',
    oemBrand: '比亚迪',
    isLiveBusiness: true,
    platformBusinessName: 'live_lead',
    supplyContentType: 'live',
    demandVolume: '直播线索 1000条',
    pushTime: '直播结束后 T+1',
    salesOwner: '销售C',
    operationOwner: '运营C',
    status: 'completed',
    requiresFirstTouch: false,
    effectiveRateRequirement: '直播线索有效率不低于 45%',
    systemDedupValid: true,
    pushSuccess: true,
    supportsPreciseDelivery: false,
    dealCycle: 'other',
    requiresDealProof: false,
    dealProofType: '无',
    requiresArrivalRecording: false,
    requiresArrivalProof: false,
    requiresSystemArrivalConfirm: false,
    maxDealsPerStore: '其他',
    storeRequirementNote: '按直播场次统计，不限制单店。',
    contractSigned: true,
    contractNo: 'HT-LIVE-202607',
    downPaymentAmount: 20000,
    downPaymentReceived: true,
    settlementMode: 'project',
    accountPeriod: '7_days',
    invoiceType: 'private_transfer',
    unitPrice: 10,
    finalUnitPrice: 9,
    finalSettlementRatio: 0.85,
    finalSettlementAmount: 7650,
    settlementStandard: '系统数据为准',
    lossRatio: 0.15,
    settlementNote: '按单场直播项目结算。',
    requirementNote: '直播基地业务，重点看场次和有效率。',
  },
]
