export interface SmartOption {
  label: string
  value: string
  pinyin: string
  initials: string
  aliases?: string[]
}

const option = (label: string, pinyin: string, initials: string, aliases: string[] = []): SmartOption => ({
  label,
  value: label,
  pinyin,
  initials,
  aliases,
})

export const cityOptions: SmartOption[] = [
  option('北京', 'beijing', 'bj'),
  option('上海', 'shanghai', 'sh'),
  option('广州', 'guangzhou', 'gz'),
  option('深圳', 'shenzhen', 'sz'),
  option('杭州', 'hangzhou', 'hz'),
  option('南京', 'nanjing', 'nj'),
  option('苏州', 'suzhou', 'sz'),
  option('成都', 'chengdu', 'cd'),
  option('重庆', 'chongqing', 'cq'),
  option('武汉', 'wuhan', 'wh'),
  option('西安', 'xian', 'xa'),
  option('天津', 'tianjin', 'tj'),
  option('郑州', 'zhengzhou', 'zz'),
  option('长沙', 'changsha', 'cs'),
  option('合肥', 'hefei', 'hf'),
  option('宁波', 'ningbo', 'nb'),
  option('青岛', 'qingdao', 'qd'),
  option('济南', 'jinan', 'jn'),
  option('厦门', 'xiamen', 'xm'),
  option('福州', 'fuzhou', 'fz'),
  option('佛山', 'foshan', 'fs'),
  option('东莞', 'dongguan', 'dg'),
  option('无锡', 'wuxi', 'wx'),
  option('常州', 'changzhou', 'cz'),
  option('南通', 'nantong', 'nt'),
  option('温州', 'wenzhou', 'wz'),
  option('金华', 'jinhua', 'jh'),
  option('石家庄', 'shijiazhuang', 'sjz'),
  option('太原', 'taiyuan', 'ty'),
  option('沈阳', 'shenyang', 'sy'),
  option('大连', 'dalian', 'dl'),
  option('长春', 'changchun', 'cc'),
  option('哈尔滨', 'haerbin', 'heb'),
  option('南昌', 'nanchang', 'nc'),
  option('南宁', 'nanning', 'nn'),
  option('昆明', 'kunming', 'km'),
  option('贵阳', 'guiyang', 'gy'),
  option('海口', 'haikou', 'hk'),
  option('兰州', 'lanzhou', 'lz'),
  option('乌鲁木齐', 'wulumuqi', 'wlmq'),
]

export const automakerOptions: SmartOption[] = [
  option('比亚迪', 'biyadai', 'byd', ['byd']),
  option('特斯拉中国', 'tesilazhongguo', 'tslzg', ['tesla', 'tesila']),
  option('理想汽车', 'lixiangqiche', 'lxqc', ['li auto', 'lixiang']),
  option('蔚来汽车', 'weilaiqiche', 'wlqc', ['nio', 'weilai']),
  option('小鹏汽车', 'xiaopengqiche', 'xpqc', ['xpeng', 'xiaopeng']),
  option('鸿蒙智行', 'hongmengzhixing', 'hmzx', ['hima', 'wenjie', 'zhijie']),
  option('赛力斯', 'sailisi', 'sls', ['seres', 'wenjie']),
  option('吉利汽车', 'jiliqiche', 'jlqc', ['geely']),
  option('极氪', 'jike', 'jk', ['zeekr']),
  option('领克', 'lingke', 'lk', ['lynk']),
  option('长城汽车', 'changchengqiche', 'ccqc', ['gwm']),
  option('长安汽车', 'changanqiche', 'caqc'),
  option('上汽集团', 'shangqijituan', 'sqjt', ['saic']),
  option('广汽集团', 'guangqijituan', 'gqjt', ['gac']),
  option('一汽集团', 'yiqijituan', 'yqjt', ['faw']),
  option('东风汽车', 'dongfengqiche', 'dfqc'),
  option('奇瑞汽车', 'qiruiqiche', 'qrqc'),
  option('零跑汽车', 'lingpaoqiche', 'lpqc', ['leapmotor']),
  option('哪吒汽车', 'nezhaqiche', 'nzqc'),
  option('上汽大众', 'shangqidazhong', 'sqdz', ['vw']),
  option('一汽大众', 'yiqidazhong', 'yqdz', ['vw']),
  option('华晨宝马', 'huachenbaoma', 'hcbm', ['bmw']),
  option('北京奔驰', 'beijingbenchi', 'bjbc', ['benz', 'mercedes']),
  option('广汽丰田', 'guangqifengtian', 'gqft', ['toyota']),
  option('一汽丰田', 'yiqifengtian', 'yqft', ['toyota']),
]

export const brandOptions: SmartOption[] = [
  option('问界', 'wenjie', 'wj', ['aito']),
  option('智界', 'zhijie', 'zj'),
  option('享界', 'xiangjie', 'xj'),
  option('尊界', 'zunjie', 'zj'),
  option('理想', 'lixiang', 'lx', ['li auto']),
  option('蔚来', 'weilai', 'wl', ['nio']),
  option('小鹏', 'xiaopeng', 'xp', ['xpeng']),
  option('比亚迪', 'biyadai', 'byd', ['byd']),
  option('腾势', 'tengshi', 'ts', ['denza']),
  option('方程豹', 'fangchengbao', 'fcb'),
  option('仰望', 'yangwang', 'yw'),
  option('特斯拉', 'tesila', 'tsl', ['tesla']),
  option('极氪', 'jike', 'jk', ['zeekr']),
  option('领克', 'lingke', 'lk', ['lynk']),
  option('银河', 'yinhe', 'yh'),
  option('哈弗', 'hafu', 'hf', ['haval']),
  option('坦克', 'tanke', 'tk'),
  option('长安启源', 'changanqiyuan', 'caqy'),
  option('深蓝', 'shenlan', 'sl'),
  option('阿维塔', 'aweita', 'awt', ['avatr']),
  option('大众', 'dazhong', 'dz', ['vw']),
  option('宝马', 'baoma', 'bm', ['bmw']),
  option('奔驰', 'benchi', 'bc', ['benz']),
  option('丰田', 'fengtian', 'ft', ['toyota']),
]

export const modelOptions: SmartOption[] = [
  option('问界 M9', 'wenjie m9', 'wjm9', ['m9', 'aito m9']),
  option('问界 M7', 'wenjie m7', 'wjm7', ['m7', 'aito m7']),
  option('问界 M5', 'wenjie m5', 'wjm5', ['m5']),
  option('智界 S7', 'zhijie s7', 'zjs7', ['s7']),
  option('理想 L9', 'lixiang l9', 'lxl9', ['l9']),
  option('理想 L8', 'lixiang l8', 'lxl8', ['l8']),
  option('理想 L7', 'lixiang l7', 'lxl7', ['l7']),
  option('理想 L6', 'lixiang l6', 'lxl6', ['l6']),
  option('蔚来 ES6', 'weilai es6', 'wles6', ['es6', 'nio es6']),
  option('蔚来 ET5', 'weilai et5', 'wlet5', ['et5']),
  option('小鹏 G9', 'xiaopeng g9', 'xpg9', ['g9', 'xpeng g9']),
  option('小鹏 G6', 'xiaopeng g6', 'xpg6', ['g6']),
  option('小鹏 P7', 'xiaopeng p7', 'xpp7', ['p7']),
  option('比亚迪 汉 DM-i', 'biyadai han dmi', 'bydhdmi', ['han', 'dmi', '汉 DM-i']),
  option('比亚迪 唐 DM-i', 'biyadai tang dmi', 'bydtdmi', ['tang', '唐 DM-i']),
  option('比亚迪 秦 PLUS', 'biyadai qin plus', 'bydqp', ['qin plus']),
  option('腾势 D9', 'tengshi d9', 'tsd9', ['d9']),
  option('方程豹 豹5', 'fangchengbao bao5', 'fcbb5', ['bao5']),
  option('特斯拉 Model Y', 'tesila model y', 'tslmy', ['model y', 'tesla y']),
  option('特斯拉 Model 3', 'tesila model 3', 'tslm3', ['model 3', 'tesla 3']),
  option('极氪 001', 'jike 001', 'jk001', ['zeekr 001']),
  option('极氪 007', 'jike 007', 'jk007', ['zeekr 007']),
  option('领克 08 EM-P', 'lingke 08 emp', 'lk08emp', ['08 emp']),
  option('大众 ID.4', 'dazhong id4', 'dzid4', ['id4', 'id.4']),
  option('宝马 i3', 'baoma i3', 'bmi3', ['bmw i3']),
  option('奔驰 EQE', 'benchi eqe', 'bceqe', ['eqe']),
]
