import { useMemo, useState } from 'react'
import { App as AntApp, Button, Card, Drawer, Form, Input, Modal, Select, Space, Table, Tag } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { accountPeriodLabels, canManageFlow, createSupplierId, isContractExpiringSoon, paymentModeLabels, phoneForRole, supplierStatusLabels, supplierTypeLabels } from '../../domain/helpers'
import { accountPeriodOptions, defaultSupplierSearchValues, defaultSupplierValues, paymentModeOptions, supplierStatusOptions, supplierTypeOptions } from '../../domain/formDefaults'
import { useLeadSystemStore } from '../../domain/store'
import type { Supplier, SupplierFormValues, SupplierSearchValues, SupplierStatus, SupplierType } from '../../domain/types'
import { PageScaffold } from '../workflows/PageScaffold'

export default function SuppliersPage() {
  const { message } = AntApp.useApp()
  const { role, suppliers, setSuppliers } = useLeadSystemStore()
  const [form] = Form.useForm<SupplierFormValues>(); const [searchForm] = Form.useForm<SupplierSearchValues>()
  const [editing, setEditing] = useState<Supplier | null>(null); const [detail, setDetail] = useState<Supplier | null>(null); const [open, setOpen] = useState(false); const [search, setSearch] = useState(defaultSupplierSearchValues)
  const filtered = useMemo(() => suppliers.filter((supplier) => !search.keyword || [supplier.name, supplier.contact, supplier.phone].some((value) => value.includes(search.keyword))), [suppliers, search])
  const selected = detail ? suppliers.find((item) => item.id === detail.id) ?? detail : null
  const create = () => { setEditing(null); form.setFieldsValue(defaultSupplierValues); setOpen(true) }
  const edit = (supplier: Supplier) => { setEditing(supplier); form.setFieldsValue(supplier); setOpen(true) }
  const save = (values: SupplierFormValues) => { if (!canManageFlow(role)) { message.warning('当前角色不能编辑供应商'); return }; if (editing) setSuppliers((current) => current.map((item) => item.id === editing.id ? { ...item, ...values } : item)); else setSuppliers((current) => [{ id: createSupplierId(current.length), ...values }, ...current]); setOpen(false); form.resetFields(); message.success('供应商已保存') }
  return <PageScaffold title="供应商管理" description="维护渠道方和数据方基础档案、合同状态与结算条件。" actions={<Button type="primary" icon={<PlusOutlined />} onClick={create}>新增供应商</Button>}>
    <Card><Form form={searchForm} layout="inline" initialValues={defaultSupplierSearchValues} onValuesChange={(_, values) => setSearch(values)}><Form.Item name="keyword"><Input allowClear placeholder="供应商、联系人、手机号" /></Form.Item><Button onClick={() => { searchForm.setFieldsValue(defaultSupplierSearchValues); setSearch(defaultSupplierSearchValues) }}>重置</Button></Form></Card>
    <Card><Table rowKey="id" dataSource={filtered} scroll={{ x: 900 }} columns={[{ title: '供应商', dataIndex: 'name', render: (_, item: Supplier) => <Button type="link" className="table-link" onClick={() => setDetail(item)}>{item.name}</Button> }, { title: '类型', dataIndex: 'type', render: (type: SupplierType) => supplierTypeLabels[type] }, { title: '联系人', dataIndex: 'contact' }, { title: '手机号', dataIndex: 'phone', render: (phone) => phoneForRole(phone, role) }, { title: '合同到期', dataIndex: 'contractEnd', render: (value, item: Supplier) => <Space>{value}{isContractExpiringSoon(item.contractEnd) ? <Tag color="orange">即将到期</Tag> : null}</Space> }, { title: '状态', dataIndex: 'status', render: (status: SupplierStatus) => <Tag>{supplierStatusLabels[status]}</Tag> }, { title: '操作', render: (_, item: Supplier) => <Button type="link" disabled={!canManageFlow(role)} onClick={() => edit(item)}>编辑</Button> }]} /></Card>
    <Modal open={open} title={editing ? '编辑供应商' : '新增供应商'} onCancel={() => setOpen(false)} onOk={() => form.submit()} destroyOnHidden><Form form={form} layout="vertical" initialValues={defaultSupplierValues} onFinish={save}><Form.Item name="name" label="供应商名称" rules={[{ required: true, message: '请输入供应商名称' }]}><Input /></Form.Item><div className="modal-form-grid"><Form.Item name="type" label="供应类型"><Select options={supplierTypeOptions} /></Form.Item><Form.Item name="status" label="合作状态"><Select options={supplierStatusOptions} /></Form.Item></div><div className="modal-form-grid"><Form.Item name="contact" label="联系人"><Input /></Form.Item><Form.Item name="phone" label="联系电话"><Input /></Form.Item></div><div className="modal-form-grid"><Form.Item name="contractStart" label="合同开始"><Input /></Form.Item><Form.Item name="contractEnd" label="合同结束"><Input /></Form.Item></div><div className="modal-form-grid"><Form.Item name="paymentMode" label="付款模式"><Select options={paymentModeOptions} /></Form.Item><Form.Item name="accountPeriod" label="账期"><Select options={accountPeriodOptions} /></Form.Item></div><Form.Item name="note" label="备注"><Input.TextArea rows={3} /></Form.Item></Form></Modal>
    <Drawer title="供应商详情" open={Boolean(selected)} onClose={() => setDetail(null)}>{selected ? <Card title={selected.name}><p>{supplierTypeLabels[selected.type]} · {selected.contact} · {phoneForRole(selected.phone, role)}</p><p>{paymentModeLabels[selected.paymentMode]} · {accountPeriodLabels[selected.accountPeriod]}</p><p>合同：{selected.contractStart} 至 {selected.contractEnd}</p><Tag>{supplierStatusLabels[selected.status]}</Tag><p>{selected.note}</p></Card> : null}</Drawer>
  </PageScaffold>
}
