import { useMemo, useState } from 'react'
import { App as AntApp, Alert, Button, Card, Form, Input, Modal, Select, Table, Tag } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { canManageFlow, createBatchId, createFollowUpId, getIneligibleDeliveryLeadIds, resolveTargetName, roleLabels } from '../../domain/helpers'
import { useLeadSystemStore } from '../../domain/store'
import type { DeliveryBatch } from '../../domain/types'
import { PageScaffold } from '../workflows/PageScaffold'

export default function BatchesPage() {
  const { message } = AntApp.useApp(); const { role, leads, targets, batches, selectedLeadIds, setBatches, setLeads, setSelectedLeadIds } = useLeadSystemStore(); const [form] = Form.useForm<{ targetId: string; note: string }>(); const [open, setOpen] = useState(false)
  const activeTargets = useMemo(() => targets.filter((target) => target.status === 'active'), [targets])
  const create = ({ targetId, note }: { targetId: string; note: string }) => { if (!canManageFlow(role)) { message.warning('当前角色不能创建交付批次'); return }; if (!selectedLeadIds.length) { message.warning('请先在线索管理中选择要交付的线索'); return }; if (getIneligibleDeliveryLeadIds(leads, selectedLeadIds).length) { message.warning('交付批次仅可包含有效线索，请重新选择'); return }; const batch: DeliveryBatch = { id: createBatchId(batches.length), targetId, leadIds: selectedLeadIds, createdBy: roleLabels[role], createdAt: '2026-07-07 16:20', status: 'delivered', note }; setBatches((current) => [batch, ...current]); setLeads((current) => current.map((lead) => selectedLeadIds.includes(lead.id) ? { ...lead, status: 'delivered', followUps: [{ id: createFollowUpId(lead.followUps.length), time: '2026-07-07 16:20', operator: roleLabels[role], content: `已创建交付批次 ${batch.id}，交付对象：${resolveTargetName(targets, targetId)}。` }, ...lead.followUps] } : lead)); setSelectedLeadIds([]); setOpen(false); form.resetFields(); message.success('交付批次已创建，所选线索状态已更新为已交付') }
  return <PageScaffold title="交付批次" description="将已选有效线索校验后下发到指定交付对象。" actions={<Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>创建批次</Button>}><Alert type="info" showIcon message={`当前已选择 ${selectedLeadIds.length} 条线索；仅“有效”状态可以创建交付批次。`} /><Card><Table rowKey="id" dataSource={batches} columns={[{ title: '批次编号', dataIndex: 'id' }, { title: '交付对象', dataIndex: 'targetId', render: (id) => resolveTargetName(targets, id) }, { title: '线索数量', dataIndex: 'leadIds', render: (ids: string[]) => ids.length }, { title: '创建人', dataIndex: 'createdBy' }, { title: '创建时间', dataIndex: 'createdAt' }, { title: '状态', dataIndex: 'status', render: () => <Tag color="purple">已交付</Tag> }]} /></Card><Modal open={open} title="创建交付批次" onCancel={() => setOpen(false)} onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={create}><Form.Item name="targetId" label="交付对象" rules={[{ required: true, message: '请选择交付对象' }]}><Select options={activeTargets.map((target) => ({ value: target.id, label: target.name }))} /></Form.Item><Form.Item name="note" label="批次备注"><Input.TextArea rows={3} /></Form.Item></Form></Modal></PageScaffold>
}
